# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_rtpois <- function(n, lambda, lower, upper) {
    .Call('_dilutionrisk_cpp_rtpois', PACKAGE = 'dilutionrisk', n, lambda, lower, upper)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_dilutionrisk_RcppExport_registerCCallable', PACKAGE = 'dilutionrisk')
})
